// CIVIC CONNECT — MULTILINGUAL UI
(() => {
  const translations = {
    en:{navHome:'Home',navReport:'Report Issue',navIssues:'Issues',navStats:'Statistics',reportNow:'Report Now',heroTag:'🌱 YOUR COMMUNITY. YOUR VOICE.',heroTitle:'Your City|Our Responsibility',heroReport:'Report an Issue',heroExplore:'Explore Community Issues',livePlatform:'● LIVE COMMUNITY PLATFORM',gpsEnabled:'GPS ENABLED',reportHeading:'Report a Problem',reportSub:'Found a problem in your community? Let us know so it can be addressed.',titlePh:'Problem Title',categoryPh:'Select a category',locationPh:'Problem Location (or use GPS)',gpsTitle:'Pin your exact spot',gpsText:'One tap finds your location and places the report there.',descPh:'Problem Description',photoTitle:'📸 Add Photos',photoOptional:'(Optional)',upload:'Upload photos',uploadHint:'Click here or drag images here',submit:'Submit Problem',issuesTag:'COMMUNITY REPORTS',issuesHeading:'Reported Issues',issuesSub:'See civic issues reported by members of the community.',search:'Search Issues',all:'All Issues',statsTag:'COMMUNITY IMPACT',statsHeading:'Civic Statistics',statsSub:'Track the impact of community reporting.',total:'Total Issues',pending:'Pending',resolved:'Resolved',tap:'Tap to view progress',trackerTag:'LIVE PROGRESS TRACKER',trackerHeading:'Civic Work Progress',trackerIntro:'See how reported problems are moving from report to resolution.',myReports:'My Reported Issues',aboutTag:'ABOUT US',aboutHeading:'Connecting Citizens With Their Community',footer:'Your voice. Your city. Your community.'},
    hi:{navHome:'होम',navReport:'समस्या रिपोर्ट करें',navIssues:'समस्याएँ',navStats:'आँकड़े',reportNow:'अभी रिपोर्ट करें',heroTag:'🌱 आपका समुदाय। आपकी आवाज़।',heroTitle:'आपका शहर|हमारी जिम्मेदारी',heroReport:'समस्या रिपोर्ट करें',heroExplore:'समुदाय की समस्याएँ देखें',livePlatform:'● लाइव कम्युनिटी प्लेटफ़ॉर्म',gpsEnabled:'GPS सक्षम',reportHeading:'समस्या की रिपोर्ट करें',reportSub:'अपने समुदाय में कोई समस्या मिली? हमें बताएं ताकि उसका समाधान हो सके।',titlePh:'समस्या का शीर्षक',categoryPh:'श्रेणी चुनें',locationPh:'समस्या का स्थान (या GPS उपयोग करें)',gpsTitle:'अपना सटीक स्थान पिन करें',gpsText:'एक टैप से आपका स्थान मिल जाएगा और रिपोर्ट वहीं दर्ज होगी।',descPh:'समस्या का विवरण',photoTitle:'📸 फ़ोटो जोड़ें',photoOptional:'(वैकल्पिक)',upload:'फ़ोटो अपलोड करें',uploadHint:'यहाँ क्लिक करें या फ़ोटो खींचकर छोड़ें',submit:'समस्या सबमिट करें',issuesTag:'सामुदायिक रिपोर्ट',issuesHeading:'रिपोर्ट की गई समस्याएँ',issuesSub:'समुदाय के सदस्यों द्वारा रिपोर्ट की गई समस्याएँ देखें।',search:'समस्याएँ खोजें',all:'सभी समस्याएँ',statsTag:'सामुदायिक प्रभाव',statsHeading:'नागरिक आँकड़े',statsSub:'सामुदायिक रिपोर्टिंग के प्रभाव को ट्रैक करें।',total:'कुल समस्याएँ',pending:'लंबित',resolved:'समाधान हो चुका',tap:'प्रगति देखने के लिए टैप करें',trackerTag:'लाइव प्रगति ट्रैकर',trackerHeading:'नागरिक कार्य प्रगति',trackerIntro:'देखें कि रिपोर्ट की गई समस्याएँ समाधान की ओर कैसे बढ़ रही हैं।',myReports:'मेरी रिपोर्ट की गई समस्याएँ',aboutTag:'हमारे बारे में',aboutHeading:'नागरिकों को उनके समुदाय से जोड़ना',footer:'आपकी आवाज़। आपका शहर। आपका समुदाय।'},
    te:{navHome:'హోమ్',navReport:'సమస్యను నివేదించండి',navIssues:'సమస్యలు',navStats:'గణాంకాలు',reportNow:'ఇప్పుడే నివేదించండి',heroTag:'🌱 మీ సమాజం. మీ స్వరం.',heroTitle:'మీ నగరం|మన బాధ్యత',heroReport:'సమస్యను నివేదించండి',heroExplore:'సమాజ సమస్యలను చూడండి',livePlatform:'● లైవ్ కమ్యూనిటీ ప్లాట్‌ఫారమ్',gpsEnabled:'GPS ప్రారంభించబడింది',reportHeading:'సమస్యను నివేదించండి',reportSub:'మీ సమాజంలో సమస్య కనిపించిందా? పరిష్కరించడానికి మాకు తెలియజేయండి.',titlePh:'సమస్య శీర్షిక',categoryPh:'వర్గాన్ని ఎంచుకోండి',locationPh:'సమస్య స్థానం (లేదా GPS ఉపయోగించండి)',gpsTitle:'ఖచ్చితమైన స్థానాన్ని పిన్ చేయండి',gpsText:'ఒక్క ట్యాప్‌తో మీ స్థానాన్ని కనుగొని అక్కడే నివేదికను ఉంచుతుంది.',descPh:'సమస్య వివరణ',photoTitle:'📸 ఫోటోలు జోడించండి',photoOptional:'(ఐచ్ఛికం)',upload:'ఫోటోలను అప్‌లోడ్ చేయండి',uploadHint:'ఇక్కడ క్లిక్ చేయండి లేదా ఫోటోలను లాగి వదలండి',submit:'సమస్యను సమర్పించండి',issuesTag:'కమ్యూనిటీ నివేదికలు',issuesHeading:'నివేదించిన సమస్యలు',issuesSub:'కమ్యూనిటీ సభ్యులు నివేదించిన సమస్యలను చూడండి.',search:'సమస్యలను శోధించండి',all:'అన్ని సమస్యలు',statsTag:'కమ్యూనిటీ ప్రభావం',statsHeading:'పౌర గణాంకాలు',statsSub:'కమ్యూనిటీ రిపోర్టింగ్ ప్రభావాన్ని ట్రాక్ చేయండి.',total:'మొత్తం సమస్యలు',pending:'పెండింగ్',resolved:'పరిష్కరించబడింది',tap:'పురోగతిని చూడటానికి ట్యాప్ చేయండి',trackerTag:'లైవ్ ప్రోగ్రెస్ ట్రాకర్',trackerHeading:'పౌర పని పురోగతి',trackerIntro:'నివేదించిన సమస్యలు పరిష్కారం వైపు ఎలా సాగుతున్నాయో చూడండి.',myReports:'నా నివేదించిన సమస్యలు',aboutTag:'మా గురించి',aboutHeading:'పౌరులను వారి సమాజంతో కలుపుతోంది',footer:'మీ స్వరం. మీ నగరం. మీ సమాజం.'},
    ta:{navHome:'முகப்பு',navReport:'பிரச்சினையைப் புகாரளிக்கவும்',navIssues:'பிரச்சினைகள்',navStats:'புள்ளிவிவரங்கள்',reportNow:'இப்போது புகாரளிக்கவும்',heroTag:'🌱 உங்கள் சமூகம். உங்கள் குரல்.',heroTitle:'உங்கள் நகரம்|நமது பொறுப்பு',heroReport:'பிரச்சினையைப் புகாரளிக்கவும்',heroExplore:'சமூகப் பிரச்சினைகளைப் பார்க்கவும்',livePlatform:'● நேரடி சமூக தளம்',gpsEnabled:'GPS இயக்கப்பட்டது',reportHeading:'ஒரு பிரச்சினையைப் புகாரளிக்கவும்',reportSub:'உங்கள் சமூகத்தில் ஒரு பிரச்சினையைக் கண்டீர்களா? தீர்வு காண எங்களுக்குத் தெரிவிக்கவும்.',titlePh:'பிரச்சினையின் தலைப்பு',categoryPh:'வகையைத் தேர்ந்தெடுக்கவும்',locationPh:'பிரச்சினை இடம் (அல்லது GPS பயன்படுத்தவும்)',gpsTitle:'உங்கள் துல்லியமான இடத்தைப் பின் செய்யவும்',gpsText:'ஒரே தட்டலில் உங்கள் இடத்தைக் கண்டறிந்து அறிக்கையை அங்கே வைக்கும்.',descPh:'பிரச்சினை விவரம்',photoTitle:'📸 புகைப்படங்களைச் சேர்க்கவும்',photoOptional:'(விருப்பம்)',upload:'புகைப்படங்களைப் பதிவேற்றவும்',uploadHint:'இங்கே கிளிக் செய்யவும் அல்லது படங்களை இழுத்து விடவும்',submit:'பிரச்சினையைச் சமர்ப்பிக்கவும்',issuesTag:'சமூக அறிக்கைகள்',issuesHeading:'புகாரளிக்கப்பட்ட பிரச்சினைகள்',issuesSub:'சமூக உறுப்பினர்கள் புகாரளித்த பிரச்சினைகளைப் பார்க்கவும்.',search:'பிரச்சினைகளைத் தேடவும்',all:'அனைத்து பிரச்சினைகள்',statsTag:'சமூக தாக்கம்',statsHeading:'குடிமக்கள் புள்ளிவிவரங்கள்',statsSub:'சமூக புகாரளிப்பின் தாக்கத்தை கண்காணிக்கவும்.',total:'மொத்த பிரச்சினைகள்',pending:'நிலுவையில்',resolved:'தீர்க்கப்பட்டது',tap:'முன்னேற்றத்தைப் பார்க்க தட்டவும்',trackerTag:'நேரடி முன்னேற்ற கண்காணிப்பு',trackerHeading:'குடிமக்கள் பணியின் முன்னேற்றம்',trackerIntro:'புகாரளிக்கப்பட்ட பிரச்சினைகள் தீர்வை நோக்கி எவ்வாறு நகர்கின்றன என்பதைப் பார்க்கவும்.',myReports:'எனது புகார்கள்',aboutTag:'எங்களைப் பற்றி',aboutHeading:'குடிமக்களை அவர்களின் சமூகத்துடன் இணைத்தல்',footer:'உங்கள் குரல். உங்கள் நகரம். உங்கள் சமூகம்.'},
    mr:{navHome:'मुख्यपृष्ठ',navReport:'समस्या नोंदवा',navIssues:'समस्या',navStats:'आकडेवारी',reportNow:'आत्ताच नोंदवा',heroTag:'🌱 तुमचा समुदाय. तुमचा आवाज.',heroTitle:'तुमचे शहर|आपली जबाबदारी',heroReport:'समस्या नोंदवा',heroExplore:'समुदायातील समस्या पहा',livePlatform:'● लाईव्ह कम्युनिटी प्लॅटफॉर्म',gpsEnabled:'GPS सक्षम',reportHeading:'समस्या नोंदवा',reportSub:'तुमच्या समुदायात समस्या आढळली? तिचे निराकरण करण्यासाठी आम्हाला कळवा.',titlePh:'समस्येचे शीर्षक',categoryPh:'श्रेणी निवडा',locationPh:'समस्येचे ठिकाण (किंवा GPS वापरा)',gpsTitle:'तुमचे अचूक ठिकाण पिन करा',gpsText:'एका टॅपमध्ये तुमचे स्थान शोधून अहवाल तिथेच ठेवला जाईल.',descPh:'समस्येचे वर्णन',photoTitle:'📸 फोटो जोडा',photoOptional:'(ऐच्छिक)',upload:'फोटो अपलोड करा',uploadHint:'येथे क्लिक करा किंवा फोटो ड्रॅग करून सोडा',submit:'समस्या सबमिट करा',issuesTag:'समुदाय अहवाल',issuesHeading:'नोंदवलेल्या समस्या',issuesSub:'समुदायातील सदस्यांनी नोंदवलेल्या समस्या पहा.',search:'समस्या शोधा',all:'सर्व समस्या',statsTag:'समुदाय प्रभाव',statsHeading:'नागरी आकडेवारी',statsSub:'समुदाय अहवालांचा परिणाम ट्रॅक करा.',total:'एकूण समस्या',pending:'प्रलंबित',resolved:'निराकरण झाले',tap:'प्रगती पाहण्यासाठी टॅप करा',trackerTag:'लाईव्ह प्रगती ट्रॅकर',trackerHeading:'नागरी कामाची प्रगती',trackerIntro:'नोंदवलेल्या समस्या निराकरणाकडे कशा जात आहेत ते पहा.',myReports:'माझ्या नोंदवलेल्या समस्या',aboutTag:'आमच्याबद्दल',aboutHeading:'नागरिकांना त्यांच्या समुदायाशी जोडणे',footer:'तुमचा आवाज. तुमचे शहर. तुमचा समुदाय.'},
    bn:{navHome:'হোম',navReport:'সমস্যা রিপোর্ট করুন',navIssues:'সমস্যা',navStats:'পরিসংখ্যান',reportNow:'এখনই রিপোর্ট করুন',heroTag:'🌱 আপনার সম্প্রদায়। আপনার কণ্ঠস্বর।',heroTitle:'আপনার শহর|আমাদের দায়িত্ব',heroReport:'সমস্যা রিপোর্ট করুন',heroExplore:'সম্প্রদায়ের সমস্যাগুলি দেখুন',livePlatform:'● লাইভ কমিউনিটি প্ল্যাটফর্ম',gpsEnabled:'GPS সক্রিয়',reportHeading:'একটি সমস্যা রিপোর্ট করুন',reportSub:'আপনার সম্প্রদায়ে কোনো সমস্যা পেয়েছেন? সমাধানের জন্য আমাদের জানান।',titlePh:'সমস্যার শিরোনাম',categoryPh:'ক্যাটাগরি নির্বাচন করুন',locationPh:'সমস্যার অবস্থান (অথবা GPS ব্যবহার করুন)',gpsTitle:'আপনার সঠিক অবস্থান পিন করুন',gpsText:'এক ট্যাপে আপনার অবস্থান খুঁজে রিপোর্টটি সেখানে রাখা হবে।',descPh:'সমস্যার বিবরণ',photoTitle:'📸 ছবি যোগ করুন',photoOptional:'(ঐচ্ছিক)',upload:'ছবি আপলোড করুন',uploadHint:'এখানে ক্লিক করুন অথবা ছবি টেনে আনুন',submit:'সমস্যা জমা দিন',issuesTag:'কমিউনিটি রিপোর্ট',issuesHeading:'রিপোর্ট করা সমস্যা',issuesSub:'কমিউনিটির সদস্যদের রিপোর্ট করা সমস্যাগুলি দেখুন।',search:'সমস্যা খুঁজুন',all:'সব সমস্যা',statsTag:'কমিউনিটি প্রভাব',statsHeading:'নাগরিক পরিসংখ্যান',statsSub:'কমিউনিটি রিপোর্টিংয়ের প্রভাব ট্র্যাক করুন।',total:'মোট সমস্যা',pending:'অপেক্ষমাণ',resolved:'সমাধান হয়েছে',tap:'অগ্রগতি দেখতে ট্যাপ করুন',trackerTag:'লাইভ প্রগ্রেস ট্র্যাকার',trackerHeading:'নাগরিক কাজের অগ্রগতি',trackerIntro:'রিপোর্ট করা সমস্যাগুলি কীভাবে সমাধানের দিকে এগোচ্ছে তা দেখুন।',myReports:'আমার রিপোর্ট করা সমস্যা',aboutTag:'আমাদের সম্পর্কে',aboutHeading:'নাগরিকদের তাদের সম্প্রদায়ের সঙ্গে যুক্ত করা',footer:'আপনার কণ্ঠস্বর। আপনার শহর। আপনার সম্প্রদায়।'}
  };

  const get = (k) => translations[localStorage.getItem('civicLanguage') || 'en'][k] || translations.en[k] || k;
  function applyLanguage(lang) {
    if (!translations[lang]) lang='en';
    localStorage.setItem('civicLanguage', lang);
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key=el.dataset.i18n, val=get(key);
      if (key==='heroTitle') { const parts=val.split('|'); el.innerHTML=`${escape(parts[0])} <span>${escape(parts[1]||'')}</span>`; }
      else el.textContent=val;
    });
    const setText=(sel,key)=>{const el=document.querySelector(sel); if(el) el.textContent=get(key)};
    const setPh=(id,key)=>{const el=document.getElementById(id); if(el) el.placeholder=get(key)};
    setText('#report h2','reportHeading'); setText('#report .section-subtitle','reportSub');
    setText('#issueForm .photo-upload-title','photoTitle');
    const opt=document.querySelector('#issueCategory option[value=""]'); if(opt) opt.textContent=get('categoryPh');
    setPh('issueTitle','titlePh'); setPh('issueLocation','locationPh'); setPh('issueDescription','descPh'); setPh('searchInput','search');
    const upload=document.querySelector('.photo-upload-label strong'); if(upload) upload.textContent=get('upload');
    const hint=document.querySelector('.photo-upload-label span:not(.photo-upload-icon)'); if(hint) hint.textContent=get('uploadHint');
    const submit=document.querySelector('#issueForm button[type="submit"]'); if(submit) submit.innerHTML=`${get('submit')} <span>→</span>`;
    const stats=document.querySelectorAll('.stat-card');
    if(stats[0]) {stats[0].querySelector('p').textContent=get('total'); stats[0].querySelector('small').textContent=get('tap');}
    if(stats[1]) {stats[1].querySelector('p').textContent=get('pending'); stats[1].querySelector('small').textContent=get('tap');}
    if(stats[2]) {stats[2].querySelector('p').textContent=get('resolved'); stats[2].querySelector('small').textContent=get('tap');}
    setText('#progressModal .section-tag','trackerTag'); setText('#progressModal h2','trackerHeading'); setText('#progressModal .progress-intro','trackerIntro'); setText('#progressModal .tracker-heading strong','myReports');
    setText('#about .section-tag','aboutTag'); setText('#about h2','aboutHeading');
    const footer=document.querySelector('footer p'); if(footer && !footer.textContent.includes('©')) footer.textContent=get('footer');
    window.dispatchEvent(new CustomEvent('civicLanguageChanged',{detail:{lang}}));
  }
  function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  window.civicTranslate=get;
  window.civicApplyLanguage=applyLanguage;
  document.addEventListener('DOMContentLoaded',()=>{
    const select=document.getElementById('languageSelect');
    const lang=localStorage.getItem('civicLanguage') || 'en';
    if(select){select.value=lang; select.addEventListener('change',()=>applyLanguage(select.value));}
    applyLanguage(lang);
  });
})();
